
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      type: apigateway-nginx
  template:
    metadata:
      labels:
        type: apigateway-nginx
    spec:
      imagePullSecrets:
        - name: dockercfg
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: function
                operator: NotIn
                values:
                - system
      containers:
      - name: apigateway-nginx
        image: airflowk8stest.azurecr.io/pumpwood/pumpwood-nginx-ssl-gateway:0.32
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1m"
        readinessProbe:
          httpGet:
            path: health-check/pumpwood-auth-app/
            port: 80
        ports:
        # Consumers Ports
        - containerPort: 80
        env:
        - name: SERVER_NAME
          value: "aks-airflow-test.brazilsouth.cloudapp.azure.com"
        - name: EMAIL
          value: "a.baceti@murabei.com"
