
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-airflow--worker
spec:
  replicas: 3
  selector:
    matchLabels:
      type: worker
      endpoint: airflow
      function: worker
  template:
    metadata:
      labels:
        type: worker
        endpoint: airflow
        function: worker
    spec:
      imagePullSecrets:
        - name: dockercfg
      volumes:
      - name: gcp--storage-key
        secret:
          secretName: gcp--storage-key
      - name: airflow--gitkey
        secret:
          secretName: airflow--gitkey
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: function
                operator: NotIn
                values:
                - system
      containers:
      - name: simple-airflow--scheduler
        image: andrebaceti/simple-airflow:0.18
        imagePullPolicy: Always
        command: ["bash"]
        args: ["/airflow/start_airflow__worker.bash"]
        resources:
          requests:
            cpu: "1m"
        volumeMounts:
          - name: gcp--storage-key
            readOnly: true
            mountPath: /etc/secrets
          - name: airflow--gitkey
            readOnly: true
            mountPath: /ssh_keys/
        ports:
        - containerPort: 8793
        env:
        - name: HASH_SALT
          valueFrom:
            secretKeyRef:
              name: hash-salt
              key: hash_salt

        # AIRFLOW
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: simple-airflow
              key: secret_key
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: simple-airflow
              key: fernet_key
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: airflow-test
        - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
          value: ""
        - name: AIRFLOW__LOGGING__REMOTE_LOGGING
          value: "False"
        - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
          value: ""
        # Ajust log collection from workers using IP address of the POD
        - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
          value: 'airflow.utils.net:get_host_ip_address'

        # Git
        - name: GIT_SERVER
          value: "github.com"
        - name: GIT_REPOSITORY
          value: "git@github.com:Murabei-OpenSource-Codes/airflow-aks-tutorial--dags.git"
        - name: GIT_BRANCH
          value: "main"

        # DATABASE
        - name: DB_HOST
          value: "postgres-simple-airflow"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simple-airflow
              key: db_password

        # RABBITMQ QUEUE
        - name: RABBITMQ_HOST
          value: "rabbitmq-main"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-main-secrets
              key: password

        ###########
        # STORAGE #
        - name: STORAGE_BUCKET_NAME
          value: airflow-test
        - name: STORAGE_TYPE
          valueFrom:
            configMapKeyRef:
              name: storage
              key: storage_type

        # GCP
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/key-storage.json"

        # AZURE
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
              secretKeyRef:
                name: azure--storage-key
                key: azure_storage_connection_string

        # AWS
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
              secretKeyRef:
                name: aws--storage-key
                key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
              secretKeyRef:
                name: aws--storage-key
                key: aws_secret_access_key
